### ISSUE TITLE
Serialize dictionnary state 

### ISSUE THREAD

**Issue by IhsenCharfi** [andybalholm/brotli#10]
I want to use brotli  for stream compression. 

I have a use case when i need to interrupt ( stop )  the stream compression for one week before continuing. For this I need to save the dictionary created already. I want to get a serialized state of the dynamic dictionary once the compression is stopped. So that, after, I will be able to de serialize the state and continue the process of compression using the dictionary created.

Is this feature/api available within this library ? 

If no,  I want to add it to this library, so from where should I start ? Can you give me some hints ?  

Are you interested in this use case to add it to the library ?

**Comment by andybalholm** [comment]
No, it’s not available. It sounds like a rather odd use case; there probably won’t be many other people who want it. So I’m not sure if it’s worth complicating the API with the option.

Andy

**Comment by IhsenCharfi** [comment]
Fair enough. But I still need to implement that feature. I looked at a few brotli Go implementations, and this one got my preference so far. Do you have any hints on where in the code I should hook, I'd appreciate it. I believe the resulting API would simply consist of a save_stae() and an init_with_state() function; you can decide when you see it whether it's too complicated for inclusion. Thanks in advance

**Comment by andybalholm** [comment]
It would just be a matter of recording the entire state of the brotli.Writer struct and everything else it points to.

But is there a good reason you couldn't finalize the compressed stream, and then decompress and recompress it when you need to append to it?
