### ISSUE TITLE
high alloc count

### ISSUE THREAD

**Issue by Azareal** [andybalholm/brotli#11]
This library seems to allocate a lot even when using Reset() to try to reuse data structures where ever possible between requests. It creates around a thousand allocs (compared to compress/gzip which appears to be zero alloc with multiple) and performs tens of times slower (according to micro benchmarks on the default quality level).

**Comment by andybalholm** [comment]
By micro-benchmarks, I assume you mean compressing tiny amounts of data. That would accentuate the overhead of the allocations. With data of significant size, the performance is much better (though still often slower than gzip, even for comparable compression). 

But I'm sure there is a lot that could be done for performance. I haven't done any optimization work at all; most of the code is just the way it came out of `c2go`.
