### ISSUE TITLE
Can you please do a simple encode and decode instructions for usage of this brotli?

### ISSUE THREAD

**Issue by gitmko0** [andybalholm/brotli#16]
Can you please do a simple encode and decode instructions for usage of this brotli?

I've only found how to encode it. How do I decode it?
https://gist.github.com/miguelmota/a0a3f18d2c6caee52508f1c393927ec6

Pls provide the instructions on your front page of github. thx

**Comment by andybalholm** [comment]
You use it basically the same way as you would use the standard compress/gzip package. The API documentation is at https://pkg.go.dev/github.com/andybalholm/brotli?tab=doc. I may add an example sometime, but you should be able to figure it out from those.

**Comment by silverwind** [comment]
Maybe put the docs link in the README.md or as the "homepage" link on GitHub?
