### ISSUE TITLE
Tag new release v1.1.0 with latest optimizations

### ISSUE THREAD

**Issue by jaimem88** [andybalholm/brotli#17]
@andybalholm the diff since the last release seems significant with a bunch of improvements and optimizations. Would you considering creating a `v1.1.0` release?

- https://github.com/andybalholm/brotli/compare/v1.0.0...master

**Comment by andybalholm** [comment]
I decided to call it v1.0.1 since there were no changes to the API.

**Comment by austincollinpena** [comment]
Love the work you put into this, thanks Andy
