### ISSUE TITLE
Panic in BestSpeed compression (version 1.0.1)

### ISSUE THREAD

**Issue by ije** [andybalholm/brotli#21]
pelase check the attched zip js file: [marked.js.zip](https://github.com/andybalholm/brotli/files/6149460/marked.js.zip)
1.0.0 is ok!

```
/usr/local/Cellar/go/1.16/libexec/src/runtime/panic.go:971 +0x499
github.com/andybalholm/brotli.compressFragmentFastImpl(0xc0002c1380, 0x31, 0x40, 0x31, 0x0, 0xc0002f8a68, 0x400, 0x400, 0x9, 0xc0002faa88, ...)
    /pkg/mod/github.com/andybalholm/brotli@v1.0.1/compress_fragment.go:382 +0x23fb
github.com/andybalholm/brotli.compressFragmentFast(0xc0002c1380, 0x31, 0x40, 0x31, 0xc0002f8a00, 0xc0002f8a68, 0x400, 0x400, 0x200, 0xc0002faa88, ...)
    /pkg/mod/github.com/andybalholm/brotli@v1.0.1/compress_fragment.go:673 +0x418
github.com/andybalholm/brotli.encoderCompressStreamFast(0xc0002f8800, 0x0, 0xc000816448, 0xc000816458, 0x16c4980)
    /pkg/mod/github.com/andybalholm/brotli@v1.0.1/encode.go:971 +0x314
github.com/andybalholm/brotli.encoderCompressStream(0xc0002f8800, 0x0, 0xc000816448, 0xc000816458, 0x10a5680)
    /pkg/mod/github.com/andybalholm/brotli@v1.0.1/encode.go:1101 +0x369
github.com/andybalholm/brotli.(*Writer).writeChunk(0xc0002f8800, 0xc0002c1380, 0x31, 0x40, 0x0, 0x1669a20, 0x0, 0x385f0b8)
    /pkg/mod/github.com/andybalholm/brotli@v1.0.1/writer.go:77 +0xba
github.com/andybalholm/brotli.(*Writer).Write(0xc0002f8800, 0xc0002c1380, 0x31, 0x40, 0xc0002f8800, 0x0, 0x3860b18)
    /pkg/mod/github.com/andybalholm/brotli@v1.0.1/writer.go:111 +0x52
github.com/ije/rex.(*responseWriter).Write(0xc0001de400, 0xc0002c1380, 0x31, 0x40, 0x163e6e0, 0x16bce00, 0x1c00000000000001)
```

**Comment by ije** [comment]
GOHOSTARCH="amd64"
GOHOSTOS="darwin"

**Comment by lifepeer** [comment]
@andybalholm Hi, I believe I've just encountered the same issue while using the [compression middleware](https://docs.gofiber.io/api/middleware/compress) for `gofiber/fiber` which relies on your łibrary. As far as I can tell, it only occurs with larger data, in this case a roughly 4.5 MB JSON response using `BestSpeed`, whereas data under 3.5-ish MB as well as `Default` and `BestCompression` variants seem to work fine.

```
panic: runtime error: index out of range [512] with length 512

github.com/andybalholm/brotli.compressFragmentFastImpl(0xc000c76000, 0x5d719, 0x5d719, 0x5d719, 0xc001802000, 0xc001278000, 0x8000, 0x8000, 0xf, 0xc00046a288, ...)
        /Users/xxx/go/pkg/mod/github.com/andybalholm/brotli@v1.0.1/compress_fragment.go:382 +0x23fb
github.com/andybalholm/brotli.compressFragmentFast(0xc000c76000, 0x5d719, 0x5d719, 0x5d719, 0xc001278000, 0xc001278000, 0x8000, 0x8000, 0x8000, 0xc00046a288, ...)
.
.
.
```

**Comment by andybalholm** [comment]
I wouldn't be surprised if v1.0.2 fixes this problem. The line where that panic happened is changed.

**Comment by lifepeer** [comment]
Ah, very well, thank you. `valyala/fasthttp` already uses v1.0.2 so once `gofiber/fiber` gets updated, I'll test it and let you know.

**Comment by andybalholm** [comment]
I think you can force your app to use v1.0.2 by specifying that in your go.mod file.

**Comment by lifepeer** [comment]
This is excellent, I didn't know it was that easy to change the version of dependencies below the second level, thanks for that!

I can now confirm that v1.0.2 does solve my issue, i.e. the same code that crashed (and still crashes when I load it) with v1.0.1  now works without a problem. Thank you for the support!

**Comment by andybalholm** [comment]
I've retracted v1.0.1 now, so that people will be less likely to use it.
