### ISSUE TITLE
New Release Soon?

### ISSUE THREAD

**Issue by stephenafamo** [andybalholm/brotli#46]
Great work on this. I see that there have been some commits since the last release (which is now more than a year old).

Do you intend to tag a new release soon?

**Comment by andybalholm** [comment]
There's only one new commit since v1.0.5. I suppose I could tag v1.0.6 if that's what people want.

**Comment by stephenafamo** [comment]
Personally, I think the "No need for content-type" is good enough for a release.

**Comment by andybalholm** [comment]
Done.
