### ISSUE TITLE
Implement io.ByteReader, io.ByteWriter & io.StringWriter interfaces

### ISSUE THREAD

**Issue by sylr** [andybalholm/brotli#47]
Hi,

I'd like to use brotli in conjunction with https://github.com/mus-format/mus-stream-go.

However, `mus-stream-go` needs the readers and writers to implement these interfaces:

https://github.com/mus-format/mus-stream-go/blob/053cf70b9133a525d368d3dc2216fc8697bd4d68/mus-stream-go.go#L5-L17

```go
package muss

import "io"

// Writer is the interface that groups the WriteByte, Write and WriteString
// methods.
type Writer interface {
	io.ByteWriter
	io.Writer
	io.StringWriter
}

// Reader is the interface that groups the basic ReadByte and Read methods.
type Reader interface {
	io.ByteReader
	io.Reader
}
```

Regards.

**Comment by andybalholm** [comment]
When you have a type that implements io.Reader or io.Writer, but doesn't have any extra methods, the easiest way to add methods like this is to wrap it in a bufio.Reader or bufio.Writer. (Don't forget to call Flush() on the bufio.Writer when you're done.)

**Comment by sylr** [comment]
All right, thank you.
