### ISSUE TITLE
Nginx incompatibility on brotli levels 10,11: multi megabyte wasm file gets truncated

### ISSUE THREAD

**Issue by litecomb** [andybalholm/brotli#48]
When I use your library in a golang webserver to serve a larger wasm file, compressed at level 10 or 11, the file will get truncated when downloaded via nginx.
The nginx is both old nginx 1.18.0 as well as new nginx 1.24 with brotli plugin installed/enabled/disabled.
Reverting to compression level 9 workarounds the problem.
The file: https://core.haircomber.com/ui/combfullui.wasm, currently served by level 9 compression.
The client requests gzip / br / deflate and my go server activates br.
Note: I don't use Content-Length and I want the file to simply pass trough nginx, which we use to add the ssl.

**Comment by andybalholm** [comment]
I'm guessing that you're triggering some kind of timeout in nginx because the file takes too long to compress.

You probably shouldn't be using such a high compression ratio to compress content on the fly. Such high compression settings are CPU-intensive enough that they should only be used to pre-compress the content, to to do it on the fly.

**Comment by andybalholm** [comment]
Even on compression level 9, your server can't nearly saturate my 4G cellular connection's bandwidth. I'm seeing a download speed of about 600 kb/s.

**Comment by litecomb** [comment]
In golang I need to compress it at max level and then cache it in ram for future requests.
The problem is the interaction with nginx
Another server in mainland europe:
https://core.haircomb.org/ui/combfullui.wasm
to try without nginx directly from golang
http://core.haircomb.org:21212/ui/combfullui.wasm

**Comment by litecomb** [comment]
Here's my compress file for reference:
https://codeberg.org/watashi564/combfullui-0.4.3-nodowntime/src/branch/master/gzip.go

**Comment by andybalholm** [comment]
The file from the direct download link loads much faster, but it isn't the same size.

**Comment by litecomb** [comment]
I understand, It is resolved.
The problem was that the user can hangup the loading of large http file, which closes the http writer, and makes the compression return an error. Then we erroneously cached the partial file.

Fixed. Thanks
