### ISSUE TITLE
Status of this library

### ISSUE THREAD

**Issue by mholt** [andybalholm/brotli#5]
Hi, this looks neat! What is the status of this library? I'd like to add this to [archiver](https://github.com/mholt/archiver) and possibly to Caddy next chance I get, if it's ready to use.

(Edit: disregard the license question, duh, for some reason I didn't see it on first pass)

**Comment by andybalholm** [comment]
I'm using it in production with github.com/andybalholm/redwood. Performance is within about 10% of using the reference implementation of Brotli with CGO.

The code is definitely not idiomatic Go, but I think it's about as readable as the original C.

**Comment by mholt** [comment]
Awesome, sounds good to me! Thanks for making this.
