### ISSUE TITLE
Tag a version for the repository for Go module consumption (v0.0.1, v0.1.0, v1.0.0, etc.)

### ISSUE THREAD

**Issue by nmiyake** [andybalholm/brotli#9]
Thank you for creating this library and updating it for Go modules!

Would it be possible to tag a release version (whether it be v0.0.1, v0.1.0, v1.0.0 etc.?) of the repository to make it easier to consume this module?

As it stands now, importing this module results in using a pseudo-version:

```
➜ go get github.com/andybalholm/brotli
go: finding github.com/andybalholm/brotli latest
go: downloading github.com/andybalholm/brotli v0.0.0-20190821151343-b60f0d972eeb
go: extracting github.com/andybalholm/brotli v0.0.0-20190821151343-b60f0d972eeb
➜ cat go.mod
module foo

go 1.13

require github.com/andybalholm/brotli v0.0.0-20190821151343-b60f0d972eeb // indirect
```

Having a tagged version would help to maintain more readable module dependencies.

**Comment by andybalholm** [comment]
Done.
